### ISSUE TITLE
Download pretrain model error

### ISSUE THREAD

**Issue by HaoYin116** [qinghuannn/PAMFN#1]
The link of pretrained models is not available in the Readme

**Comment by qinghuannn** [comment]
I confirmed that this link is available  and I can download the pre-trained model through this [link ](https://1drv.ms/u/s!ApyE_Lf3PFl2itlpIvyjNzcQ0TlsPA?e=biQ4bw).
![image](https://github.com/qinghuannn/PAMFN/assets/24269148/8900c0dd-2736-4105-b0aa-2683315947ad)
